version: '3.8'
services:
  web:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - SOVEREIGN_OVERLAY_CONFIG_PATH=config/sovereign_overlay.yaml
